from src.funcs.leaver import leaver
from src.funcs.serverchecker import serverchecker
from src.funcs.channelchecker import channelchecker
from src.funcs.channelspammer import channelspammer
from src.funcs.checker import checker
from src.funcs.biochanger import biochanger
from src.funcs.displaynamechanger import displaynamechanger
from src.funcs.nicknamechanger import nicknamechanger
from src.funcs.suppliers import suppliers
from src.funcs.verifybypasses.verifybypasses import verifybypasses